version: "3.9"

services:
  cart-db:
    image: postgres:15.1
    container_name: cart-db
    restart: always
    network_mode: bridge
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: cart_db